// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: AppServer.proto
#ifndef GRPC_AppServer_2eproto__INCLUDED
#define GRPC_AppServer_2eproto__INCLUDED

#include "AppServer.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace AppServer {

// The service definition.
class AlgoServer final {
 public:
  static constexpr char const* service_full_name() {
    return "AppServer.AlgoServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status Request(::grpc::ClientContext* context, const ::AppServer::AppRequest& request, ::AppServer::AppReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AppServer::AppReply>> AsyncRequest(::grpc::ClientContext* context, const ::AppServer::AppRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AppServer::AppReply>>(AsyncRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AppServer::AppReply>> PrepareAsyncRequest(::grpc::ClientContext* context, const ::AppServer::AppRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AppServer::AppReply>>(PrepareAsyncRequestRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Sends a greeting
      virtual void Request(::grpc::ClientContext* context, const ::AppServer::AppRequest* request, ::AppServer::AppReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Request(::grpc::ClientContext* context, const ::AppServer::AppRequest* request, ::AppServer::AppReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Request(::grpc::ClientContext* context, const ::AppServer::AppRequest* request, ::AppServer::AppReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AppServer::AppReply>* AsyncRequestRaw(::grpc::ClientContext* context, const ::AppServer::AppRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AppServer::AppReply>* PrepareAsyncRequestRaw(::grpc::ClientContext* context, const ::AppServer::AppRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Request(::grpc::ClientContext* context, const ::AppServer::AppRequest& request, ::AppServer::AppReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AppServer::AppReply>> AsyncRequest(::grpc::ClientContext* context, const ::AppServer::AppRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AppServer::AppReply>>(AsyncRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AppServer::AppReply>> PrepareAsyncRequest(::grpc::ClientContext* context, const ::AppServer::AppRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AppServer::AppReply>>(PrepareAsyncRequestRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Request(::grpc::ClientContext* context, const ::AppServer::AppRequest* request, ::AppServer::AppReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Request(::grpc::ClientContext* context, const ::AppServer::AppRequest* request, ::AppServer::AppReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Request(::grpc::ClientContext* context, const ::AppServer::AppRequest* request, ::AppServer::AppReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::AppServer::AppReply>* AsyncRequestRaw(::grpc::ClientContext* context, const ::AppServer::AppRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::AppServer::AppReply>* PrepareAsyncRequestRaw(::grpc::ClientContext* context, const ::AppServer::AppRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Request_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status Request(::grpc::ServerContext* context, const ::AppServer::AppRequest* request, ::AppServer::AppReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Request() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::AppServer::AppRequest* /*request*/, ::AppServer::AppReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequest(::grpc::ServerContext* context, ::AppServer::AppRequest* request, ::grpc::ServerAsyncResponseWriter< ::AppServer::AppReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Request<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Request() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::AppServer::AppRequest, ::AppServer::AppReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::AppServer::AppRequest* request, ::AppServer::AppReply* response) { return this->Request(context, request, response); }));}
    void SetMessageAllocatorFor_Request(
        ::grpc::experimental::MessageAllocator< ::AppServer::AppRequest, ::AppServer::AppReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::AppServer::AppRequest, ::AppServer::AppReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::AppServer::AppRequest* /*request*/, ::AppServer::AppReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Request(
      ::grpc::CallbackServerContext* /*context*/, const ::AppServer::AppRequest* /*request*/, ::AppServer::AppReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Request(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::AppServer::AppRequest* /*request*/, ::AppServer::AppReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Request<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Request<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Request() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::AppServer::AppRequest* /*request*/, ::AppServer::AppReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Request() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::AppServer::AppRequest* /*request*/, ::AppServer::AppReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequest(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Request() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Request(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::AppServer::AppRequest* /*request*/, ::AppServer::AppReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Request(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Request(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Request() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::AppServer::AppRequest, ::AppServer::AppReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::AppServer::AppRequest, ::AppServer::AppReply>* streamer) {
                       return this->StreamedRequest(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::AppServer::AppRequest* /*request*/, ::AppServer::AppReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRequest(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::AppServer::AppRequest,::AppServer::AppReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Request<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Request<Service > StreamedService;
};

}  // namespace AppServer


#endif  // GRPC_AppServer_2eproto__INCLUDED
