// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: AppServer.proto

#include "AppServer.pb.h"
#include "AppServer.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace AppServer {

static const char* AlgoServer_method_names[] = {
  "/AppServer.AlgoServer/Request",
};

std::unique_ptr< AlgoServer::Stub> AlgoServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AlgoServer::Stub> stub(new AlgoServer::Stub(channel));
  return stub;
}

AlgoServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Request_(AlgoServer_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AlgoServer::Stub::Request(::grpc::ClientContext* context, const ::AppServer::AppRequest& request, ::AppServer::AppReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AppServer::AppRequest, ::AppServer::AppReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Request_, context, request, response);
}

void AlgoServer::Stub::experimental_async::Request(::grpc::ClientContext* context, const ::AppServer::AppRequest* request, ::AppServer::AppReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AppServer::AppRequest, ::AppServer::AppReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Request_, context, request, response, std::move(f));
}

void AlgoServer::Stub::experimental_async::Request(::grpc::ClientContext* context, const ::AppServer::AppRequest* request, ::AppServer::AppReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Request_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AppServer::AppReply>* AlgoServer::Stub::PrepareAsyncRequestRaw(::grpc::ClientContext* context, const ::AppServer::AppRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AppServer::AppReply, ::AppServer::AppRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Request_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AppServer::AppReply>* AlgoServer::Stub::AsyncRequestRaw(::grpc::ClientContext* context, const ::AppServer::AppRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

AlgoServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AlgoServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AlgoServer::Service, ::AppServer::AppRequest, ::AppServer::AppReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AlgoServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AppServer::AppRequest* req,
             ::AppServer::AppReply* resp) {
               return service->Request(ctx, req, resp);
             }, this)));
}

AlgoServer::Service::~Service() {
}

::grpc::Status AlgoServer::Service::Request(::grpc::ServerContext* context, const ::AppServer::AppRequest* request, ::AppServer::AppReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace AppServer

